version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: a_gnri_database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: a_gnri_1234 # 실제 사용 시 보안 강화 필요
      POSTGRES_DB: global_news_db
    ports:
      - "5432:5432"
    volumes:
      # 호스트의 'pg_data' 디렉토리에 데이터를 영구 저장
      - ./pg_data:/var/lib/postgresql/data

  pgadmin: # 시각적 관리를 위한 툴 (선택사항)
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin