version: '3.8'

services:
  db:
    image: postgres:16
    container_name: a_gnri_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgre0721!
      POSTGRES_DB: a_gnri_db
    ports:
      - "25725:5432"
    volumes:
      - /opt/a_gnri_pgdata:/var/lib/postgresql/data

  